configuracion_basica = {
    "limite": 15,
    "dont_spam": 1,
    "rutina_timer": 15,
}

admins = ["hablemosdepavadaspod","demian762","everovius","juancatera","pointandclickstore","lulumy27","mat_max_hdp","wansaia"]

lista_redes = [
    "¡Seguinos en Instagram! https://www.instagram.com/hablemosdepavadas/",
    "Acordate que resubimos CASI todo a YouTube https://www.youtube.com/@hablemosdepavadas",
    "¿Tenemos TikTok? parece que si... https://www.tiktok.com/@hablemosdepavadas",
    "¿Te gustan los podcasts? seguinos en Spotify https://open.spotify.com/show/2sC1753wCmhBnDkZx7UOyj",
    "¡Sumate a nuestro Discord! https://discord.gg/YDdPMDxFDd",
]

lista_amigos = [
    "La recomendación de la casa, seguilo a Sergio de Point and Click Store https://www.instagram.com/pointandclickstore/",
    "El mago de las impresoras 3D, mirá eso!! POPLAND customs https://www.instagram.com/poplandcustoms/",
    "¿Te van el cine y las entrevistas? seguilo a Tobi en https://www.instagram.com/soytoubi/",
    "¿Necesitás un actor profesional? Acá tenés uno: Ariel Barañano Actor Profesional https://www.instagram.com/ariel.baranano/",
    "¿Estás duro de tanto gaming? Llamalo a Javy el masajista: https://www.instagram.com/med.trad.china.javier?igsh=MTBmOGdlZmZ2Y2pwOQ==",
    "Te vas a volver loco con los pines de funkonauta! buscalos en su IG https://www.instagram.com/funkonauta/"
]

spam_messenges = [
    "HOLA",
    "VENGO A SPAMEAR",
    "SEGURO QUE HAY ALGO QUE QUIEREN TAPAR",
    "ASI QUE NO SE LES OCURRA HACER SCROLL PARA ARRIBA",
    "BUENO",
    "SE ME ACABO RAPIDO LA IMAGINACION",
    "PERO SE QUE PUEDO HACER ALGO PARA SPAMEAR",
    "PUEDO REPETIR TRES VECES ESTA LISTA DE MENSAJES!"
]


cafecito_texto = "Si les gusta nuestro contenido pueden ayudarnos con un cafecito a https://cafecito.app/hablemosdepavadas"

rutina_lista = [lista_redes,[cafecito_texto]]

grog_list = [
    "Una pinta de grog para el Bot!",
    "¡¡¡Otra pinta de grog para el Bot!!!",
    "Un brindis por las aventuras gráficas!!",
    "oootrhra pintita pal boott...",
    "otra maz??, bueno a ver dale....",
    "oi no manejoo.... vine en auto???",
    "pará pará ke tngo ke..... WAAAAA ..... a veh, dame dale....",
]

coma_etilico_list = [
    "El bot está en coma etílico.",
    "El bot se fue a una reunión de alcohólicos anónimos.",
    "El bot está.... indispuesto.",
    "Alguien que le de un vasito de agua al bot.",
    "¡HIC!",
    "El bot está llamando a Hugo",
    "Quedó re duro el bot..."
]

insultos_dict = {
    1:"¿Has dejado ya de usar pañales?",
    2:"¡No hay palabras para describir lo asqueroso que eres!",
    3:"¡He hablado con simios más educados que tu!",
    4:"¡Llevarás mi espada como si fueras un pincho moruno!",
    5:"¡Luchas como un ganadero!",
    6:"¡No pienso aguantar tu insolencia aquí sentado!",
    7:"¡Mi pañuelo limpiará tu sangre!",
    8:"¡Ha llegado tu HORA, palurdo de ocho patas!",
    9:"¡Una vez tuve un perro más listo que tu!",
    10:"¡Nadie me ha sacado sangre jamás, y nadie lo hará!",
    11:"¡Me das ganas de vomitar!",
    12:"¡Tienes los modales de un mendigo!",
    13:"¡He oído que eres un soplón despreciable!",
    14:"¡La gente cae a mis pies al verme llegar!",
    15:"¡Demasiado bobo para mi nivel de inteligencia!",
    16:"¡Obtuve esta cicatriz en una batalla a muerte!",
}

respuestas_dict = {
    1:"¿Por qué? ¿Acaso querías pedir uno prestado?",
    2:"Sí que las hay, sólo que nunca las has aprendido.",
    3:"Me alegra que asistieras a tu reunión familiar diaria.",
    4:"Primero deberías dejar de usarla como un plumero.",
    5:"Qué apropiado, tú peleas como una vaca.",
    6:"Ya te están fastidiando otra vez las almorranas, ¿Eh?",
    7:"Ah, ¿Ya has obtenido ese trabajo de barrendero?",
    8:"Y yo tengo un SALUDO para ti, ¿Te enteras?",
    9:"Te habrá enseñado todo lo que sabes.",
    10:"¿TAN rápido corres?",
    11:"Me haces pensar que alguien ya lo ha hecho.",
    12:"Quería asegurarme de que estuvieras a gusto conmigo.",
    13:"Qué pena me da que nadie haya oído hablar de ti",
    14:"¿Incluso antes de que huelan tu aliento?",
    15:"Estaría acabado si la usases alguna vez.",
    16:"Espero que ya hayas aprendido a no tocarte la nariz.",
}

trivia = {
    "El nombre oficial de la tienda de vudú es:": ["La Casa Internacional de Vudú", "Vudú y Más", "La Tienda de Vudú", "La Casa Internacional de Mojo"],
    "El juego de Monkey Island antes se llamaba:": ["Mutiny on Monkey Island", "Voyage to the Monkey Island", "The Pirates of Monkey Island", "El juego de los piratas"],
    "La capitana Kate Capsize:": [ "Fue encarcelada injustamente por cargos falsos", "Dirige una tienda de ataúdes de segunda mano en la isla Phatt", "Se hizo gobernadora de la isla Mêlée", "No aparece en ningún juego de Monkey Island"],
    "Al fondo del Scumm Bar está:": ["La cocina", "La bodega", "Un trofeo de pesca", "Una ballena gigante"],
    "Morgan LeFlay apareció primero en:": ["Tales of Monkey Island", "LeChuck's Revenge", "La Fuga de Monkey Island", "The Secret of Monkey Island"],
    "¿Quién es el experto local sobre 'Loom'?": ["Cobb", "Cal Bob", "El vigía", "Wally"],
    "¿Cuál de estos ingredientes no hace falta para llegar a Monkey Island?": ["Levadura", "Sangre de mono", "Calavera", "Canela"],
    "La tienda de Wally está en:": ["La calle Menor", "Una lista de vigilancia policial", "La calle Mayor", "La calle A"],
    "El circo de la isla Melée era de:": ["Los Hermanos Fettucini", "Los Amigos Gazpacho", "Los Chicos Espaguetis", "Los Hombres de Baja Fibra Moral"],
    "En Monkey Island 2, ¿quién tenía un barco con fondo de cristal?": ["Kate Capsize", "Capitán Dread", "Guybrush", "Stan"],
    "La isla Escorbuto es famosa por:": ["Las limas", "Ser el coto de pesca de Bella", "El ocio nocturno", "Un brote de escorbuto"],
    "El nombre de la hechicera vudú es:": ["Corina", "Isabel", "No tiene nombre", "Hechicera vudú"],
    "¿Cuál de estos ingredientes no hace falta para elaborar un muñeco vudú?": ["Algo del huerto", "Algo de los muertos", "Algo de tela", "Algo de la cabeza"],
    "El Mono Loco era:": ["Un barco con un mascarón de proa en forma de mono", "El chimpancé de LeChuck", "Un mono robot gigante", "El líder de los piratas de la cueva Periglo"],
    "¿Cuántos prisioneros hay en la cantera de hielo?": ["21", "12", "16", "No existe la cantera de hielo"],
    "La frase de Guybrush para distraer a la gente suele ser:": ["Mira detrás de ti, ¡un mono con tres cabezas!", "¡Soy Murray! ¡La demoníaca e invencible calavera!", "Vendo estas bonitas chaquetas de piel", "¡Madre de Dios! ¡Es el pollo diablo!"],
    "Dave Grossman empezó a trabajar en Lucasfilm Games en:": ["1989", "1987", "1990", "1988"],
    "Guybrush lleva puestos:": ["Bóxers", "Slips", "No se sabe", "Nada"],
    "El primer Monkey Island salió para:": ["IBM PC", "Atari ST", "C64", "Amiga"],
    "El desarrollo del primer Monkey Island fueron:": ["9 meses", "Tiempos durísimos para el equipo", "22 meses", "16 meses"],
    "El primer juego en usar el sistema SCUMM:": ["Maniac Mansion", "The Secret of Monkey Island", "Loom", "Day of the Tentacle"],
    "¿Qué ave aparece en el sello de Brrr Muda?": ["Un loro", "Una lechuza de las nieves", "Un mono", "Un águila"],
    "¿Cuántas preguntas tiene el formulario de Brr Muda?": ["33", "26", "52", "42"],
    "El loro del blasón de Brr Muda sostiene...": ["Espadas", "Balas de cañón", "Galletas", "Carámbanos"],
    "En la isla Blood está:": ["El Hotel Sopabuena", "La Costa de los Barberos", "El malvado pirata Bloodnose", "Las Agradables Criptas de Stan"],
    "¿Cuánto tiempo aguanta Guybrush sin respirar bajo el agua en este juego?": ["8 minutos", "10 minutos", "22 minutos", "6 minutos"],
    "Al final de Monkey Island 1, LeChuck es derrotado:": ["Con cerveza de raíz", "Con explosivos", "En un duelo a espada con insultos", "Con un muñeco vudú"],
    "¿Qué hay tallado en un árbol de la playa de Monkey Island?": ["L + E", "TQM", "XD", "G + E"],
    "¿Cuántas ventanas iluminadas hay en la mansión de la gobernadora?": ["Dieciocho", "Dieciséis", "Veinte", "¿Eh?"],
    "En el puerto de escorbutifarras hay una enorme...": ["Mosca", "Cucaracha", "Lombriz", "Escorbutifarra"],
    "Los banderines del parque de atracciones son:": ["Rojos y amarillos", "Rojos y verdes", "Amarillos y verdes", "Azules y verdes"],
    "Las flores que hay junto al banco son:": ["Moradas", "Rojas", "Rosas", "Amarillas"],
    "¿Cuál de estos libros no se encuentra en la librería de Carla?": ["Piratería para lerdos", "Estrategias de combate náuticas", "Trucos vudú caseros", "La autobiografía de Jon Laney"],
    "La pata del parque se puede alimentar con:": ["Pan", "Comida para patos", "Pescado", "Galletas"],
    "Dee habla sin cesar sobre:": ["Anclas", "Piratas", "Lucha con espada", "Barcos"],
    "¿Quién es el editor de El Heraldo Pirata?": ["Conrad Lee", "Davy Jones", "Cerra Jera", "Englebert LeCrust"],
    "¿De quién es el velo nupcial que hay en el camarote de LeChuck?": ["De Elaine", "De Murray", "De Putra", "De LeChuck"],
    "¿El suelo de qué habitación no para de revolverse?": ["El camarote de LeChuck", "El puesto de vigía", "El acantilado de Monkey Island", "La cocina del Scumm Bar"],
    "¿Qué pone en el letrero fuera de la cabeza de mono?": ["Propiedad privada", "Aviso: serpientes venenosas", "Aquí yace Pincho Moruno", "Prohibido comerse los lagartos"],
    "El pollo fantasma con problemas digestivos se llama:": ["Piquita", "Lola", "Paquita", "Madison"],
    "¿Cuál es la primera norma de la cárcel de Melée?": ["Prohibido fugarse", "Prohibidos los pasteles", "Prohibido correr", "Prohibido dar de comer a las ratas"],
    "¿Qué criatura de alta mar se puede ver nadando desde la cofa de LeBarco?": ["Tiburón", "Calamar", "Barracuda", "Kraken"],
    "El escudo de armas del castillo de hielo de Brrr Muda está formado por:": ["Una espada y dos peces", "Una espada pez", "Un pez espada", "Un pez y dos espadas"],
    "El ave de la playa de la isla Escorbuto es:": ["Ave escarlata que apunta y picotea", "Robalimas petiamarillo", "Ave alirroja que parsea líneas de comandos", "Pájaro del trueno de pico azul"],
    "¿Qué animal figura en el barco de Bella Fisher?": ["Un perro", "Un narval", "Un pez", "Un plátano viejo"],
    "¿Cómo se llama el pirata pícaro del libro favorito de Herman?": ["Reginald", "Harry", "Ron", "Barbabalandro"],
    "¿Cuántos cuervos hay en la cofa de LeBarco?": ["Cero", "Doce", "Uno", "Tres"],
    "¿Qué especie marina no se halla en la pescadería de Mêlée?": ["Calamar", "Pez hinchado", "Pez sapo", "Pez grumo"],
    "Un brote de escorbuto obliga a todos los barcos que vayan al norte de la isla Escorbuto a transportar:": ["Limas", "Limones", "Plátanos", "Uvas"],
    "El contable de Stan se llama:": ["Ned", "Ed", "Fred", "Ted"],
    "¿Cuántos loros hay junto al puesto de escorbutifarras?": ["Uno", "Ninguno", "Dos", "Tres"],
    "El vendedor de escorbutifarras:": ["Es miope", "No tiene olfato", "No oye bien", "No sabe cantar"],
    "¿Qué hay junto a un camino sin salida en la isla Terror?": ["Un árbol inclinado", "Un mono", "Una estatua espeluznante", "Pirañas"],
    "¿Dónde hay espinos?": ["En la isla Terror", "En la isla Mínima", "En la isla Escorbuto", "En la isla Melée"],
    "¿Cuántos esqueletos hay flotando en la playa de la isla Terror?": ["Dos", "Uno", "Cuatro", "Ocho"],
    "¿Cuál de estos no está en el parque?": ["Un balancín", "Un pozo", "Un columpio", "Un ancla"],
    "La amiga de Chuckie se llama:": ["Dee", "Lil", "Lela", "No tiene nombre"],
    "La pareja del parque está dando de comer a:": ["Una pata", "Una paloma", "Un ciervo", "Una ardilla"],
    "En el parque hay:": ["Todas las respuestas", "Un columpio", "Un pozo", "Un barco"]
}

trivia_limite = {
    'El nombre oficial de la tienda de vudú es:': 4,
    'El juego de Monkey Island antes se llamaba:': 11,
    'La capitana Kate Capsize:': 35,
    'Al fondo del Scumm Bar está:': 4,
    'Morgan LeFlay apareció primero en:': 8,
    "¿Quién es el experto local sobre 'Loom'?": 4,
    '¿Cuál de estos ingredientes no hace falta para llegar a Monkey Island?': 5,
    'La tienda de Wally está en:': 2,
    'El circo de la isla Melée era de:': 13,
    'En Monkey Island 2, ¿quién tenía un barco con fondo de cristal?': 10,
    'La isla Escorbuto es famosa por:': 14,
    'El nombre de la hechicera vudú es:': 6,
    '¿Cuál de estos ingredientes no hace falta para elaborar un muñeco vudú?': 5,
    'El Mono Loco era:': 35,
    '¿Cuántos prisioneros hay en la cantera de hielo?': 2,
    'La frase de Guybrush para distraer a la gente suele ser:': 31,
    'Dave Grossman empezó a trabajar en Lucasfilm Games en:': 1,
    'Guybrush lleva puestos:': 5,
    'El primer Monkey Island salió para:': 5,
    'El desarrollo del primer Monkey Island fueron:': 2,
    'El primer juego en usar el sistema SCUMM:': 13,
    '¿Qué ave aparece en el sello de Brrr Muda?': 2,
    '¿Cuántas preguntas tiene el formulario de Brr Muda?': 2,
    'El loro del blasón de Brr Muda sostiene...': 6,
    'En la isla Blood está:': 16,
    '¿Cuánto tiempo aguanta Guybrush sin respirar bajo el agua en este juego?': 1,
    'Al final de Monkey Island 1, LeChuck es derrotado:': 14,
    '¿Qué hay tallado en un árbol de la playa de Monkey Island?': 1,
    '¿Cuántas ventanas iluminadas hay en la mansión de la gobernadora?': 4,
    'En el puerto de escorbutifarras hay una enorme...': 6,
    'Los banderines del parque de atracciones son:': 7,
    'Las flores que hay junto al banco son:': 4,
    '¿Cuál de estos libros no se encuentra en la librería de Carla?': 16,
    'La pata del parque se puede alimentar con:': 5,
    'Dee habla sin cesar sobre:': 4,
    '¿Quién es el editor de El Heraldo Pirata?': 6,
    '¿De quién es el velo nupcial que hay en el camarote de LeChuck?': 6,
    '¿El suelo de qué habitación no para de revolverse?': 14,
    '¿Qué pone en el letrero fuera de la cabeza de mono?': 21,
    'El pollo fantasma con problemas digestivos se llama:': 1,
    '¿Cuál es la primera norma de la cárcel de Melée?': 6,
    '¿Qué criatura de alta mar se puede ver nadando desde la cofa de LeBarco?': 6,
    'El escudo de armas del castillo de hielo de Brrr Muda está formado por:': 9,
    'El ave de la playa de la isla Escorbuto es:': 26,
    '¿Qué animal figura en el barco de Bella Fisher?': 3,
    '¿Cómo se llama el pirata pícaro del libro favorito de Herman?': 6,
    '¿Cuántos cuervos hay en la cofa de LeBarco?': 3,
    '¿Qué especie marina no se halla en la pescadería de Mêlée?': 7,
    'Un brote de escorbuto obliga a todos los barcos que vayan al norte de la isla Escorbuto a transportar:': 3,
    'El contable de Stan se llama:': 1,
    '¿Cuántos loros hay junto al puesto de escorbutifarras?': 3,
    'El vendedor de escorbutifarras:': 9,
    '¿Qué hay junto a un camino sin salida en la isla Terror?': 12,
    '¿Dónde hay espinos?': 5,
    '¿Cuántos esqueletos hay flotando en la playa de la isla Terror?': 3,
    '¿Cuál de estos no está en el parque?': 5,
    'La amiga de Chuckie se llama:': 3,
    'La pareja del parque está dando de comer a:': 3,
    'En el parque hay:': 17
 }



